services:
  app:
    container_name: saboresapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL:  jdbc:postgresql://root:W53HlSLmzQjmTyMs0RG0KrDO0xNx5cpn@dpg-csr35g68ii6s73f3jlr0-a/sabores
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: W53HlSLmzQjmTyMs0RG0KrDO0xNx5cpn
    networks:
      - sabores-network
  db:
    container_name: saboresdb
    image: postgres:16.4-alpine3.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: W53HlSLmzQjmTyMs0RG0KrDO0xNx5cpn
      POSTGRES_DB:
    networks:
      - restaurant-network
    healthcheck:
      # Use the CMD-SHELL command to check the health
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      # Set the interval to 10 seconds
      interval: 10s
      # Set the timeout to 5 seconds
      timeout: 5s
      # Set the retries to 5
      retries: 5
    volumes:
      - dpg-csr35g68ii6s73f3jlr0-a-data:/var/lib/postgresql/data

volumes:
  resturantdb_yi66-data:

networks:
  restaurant-network: