services:
  app:
    image: 'sabores-api:dev'
    build:
      context: src/main/java/guia/saboresapi
      dockerfile: Dockerfile
    container_name: sabores-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://root:W53HlSLmzQjmTyMs0RG0KrDO0xNx5cpn@dpg-csr35g68ii6s73f3jlr0-a/sabores
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=W53HlSLmzQjmTyMs0RG0KrDO0xNx5cpn
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
  db:
    image: postgres
    container_name: saboresdb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: W53HlSLmzQjmTyMs0RG0KrDO0xNx5cpn
      POSTGRES_DB: sabores
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: